openapi: 3.0.2
info:
  title: Documentation for Images API
  description: Documented API endpoints for images API

servers:
- url: http://photos.local/api/
  description: Local server

components:
  schemas:
    Post:
      type: object
      properties:
        title:
          type: string
          example: Coffee table review

    Product:
      type: object
      properties:
        name:
          type: string
          example: Coffee table
        category:
          type: string
          example: Home

    Image:
      type: object
      properties:
        filename:
          type: string
          example: image.png
        model:
          type: object
          oneOf:
          - $ref: '#/components/schemas/Post'
          - $ref: '#/components/schemas/Product'

    ImageWithId:
      type: object
      allOf:
      - $ref: '#/components/schemas/Image'
      - type: object
        properties:
          id:
            type: integer
            example: 1

  parameters:
    idInPath:
      in: path
      name: id
      schema:
        type: integer
  responses:
    SuccessImageResponse:
      content:
        application/json:
          schema:
            type: object
            $ref: '#/components/schemas/ImageWithId'
    SuccessfullyCreatedProduct:
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Successfully created Product

  requestBodies:
    saveRequest:
      content:
        application/json:
          schema:
            type: object
            oneOf:
            - $ref: '#/components/schemas/Post'
            - $ref: '#/components/schemas/Product'
            properties:
              photos:
                type: string
                example: image.jpg, image.png

paths:
  /photos:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  photos:
                    type: array
                    items:
                      $ref: '#/components/schemas/ImageWithId'
  /photos/{id}:
    get:
      parameters:
      - $ref: '#/components/parameters/idInPath'
      responses:
        '200':
          $ref: '#/components/responses/SuccessImageResponse'
  /posts/create:
    post:
      requestBody:
        $ref: '#/components/requestBodies/saveRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Successfully created Post

  /products/create:
    post:
      requestBody:
        $ref: '#/components/requestBodies/saveRequest'
      responses:
        '200':
          $ref: '#/components/responses/SuccessfullyCreatedProduct'

